version: '3.8'

services:
  ###############################
  # Microservices configuration #
  ###############################
  api-gateway:
    build: 
      context: ./GSWB.APIGateway
      dockerfile: ./src/APIGateway.API/Dockerfile.debug
      
  swarm-bot:
    build: 
      context: ./GSWB.SwarmBot
      dockerfile: ./src/SwarmBot.API/Dockerfile.debug

  members:
    build: 
      context: ./GSWB.Members
      dockerfile: ./src/Members.API/Dockerfile.debug

  ###################################
  # Microservices configuration end #
  ###################################